# Generated by Django 5.2 on 2025-04-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.JSONField(default=list)),
                ("conference", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("field", models.CharField(blank=True, max_length=255, null=True)),
                ("keywords", models.JSONField(default=list)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                ("is_interesting", models.BooleanField(default=False)),
                ("is_downloaded", models.BooleanField(default=False)),
                ("is_uploaded", models.BooleanField(default=True)),
                ("file", models.FileField(upload_to="papers/")),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
