# Generated by Django 5.2 on 2025-04-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="bibtex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="sourceCode",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
