# Generated by Django 5.2 on 2025-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_paper_bibtex_paper_sourcecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
