# Generated by Django 5.2 on 2025-04-18 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_publication"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="publication",
            table="Publications",
        ),
    ]
