# Generated by Django 5.2 on 2025-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_publication_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="publication",
            table=None,
        ),
    ]
