# Generated by Django 5.2 on 2025-04-18 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_publication_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="publication",
            table="users_publication",
        ),
    ]
