# Generated by Django 5.2 on 2025-04-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_auto_20250419_1628"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("count", models.IntegerField(default=0)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="users.paper",
                    ),
                ),
            ],
            options={
                "unique_together": {("paper", "year")},
            },
        ),
    ]
