# Generated by Django 5.2 on 2025-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_papercitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
