# Generated by Django 5.2 on 2025-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_userprofile_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="additional_keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
