# Generated by Django 5.2 on 2025-04-21 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_userprofile_additional_keywords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="keywords",
            new_name="research_interests",
        ),
    ]
