# Generated by Django 5.2 on 2025-04-19 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('research_interests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('conference', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('field', models.CharField(blank=True, max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('downloadUrl', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('method', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
                ('bibtex', models.TextField(blank=True)),
                ('sourceCode', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_type', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('citation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(blank=True, related_name='datasets', to='public_api.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_publications', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='InterestingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='public_api.Paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_interesting_papers', to='auth.user')),
            ],
            options={
                'unique_together': {('user', 'paper')},
            },
        ),
    ]
