# Generated by Django 5.2 on 2025-06-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='conference',
        ),
    ]
