# Generated by Django 5.2 on 2025-06-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0003_remove_dataset_tasks_remove_paper_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='conference_venue',
            new_name='conference',
        ),
    ]
