# Generated by Django 5.2 on 2025-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0004_rename_conference_venue_paper_conference'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['-publication_date'], name='papers_publica_b611b5_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['title'], name='papers_title_ca7740_idx'),
        ),
    ]
