# Generated by Django 5.2.4 on 2025-04-20 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_api', '0004_dataset_similar_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_users', to='public_api.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_downloaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='InterestingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='public_api.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_interesting_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dataset')},
            },
        ),
    ]
