# Generated by Django 5.2 on 2025-09-27 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0005_paper_papers_publica_b611b5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['id'], name='conference_id_26d896_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['name'], name='conference_name_383dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['rank'], name='conference_rank_ba3268_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['-created_at'], name='conference_created_5fb800_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['id'], name='journal_id_64eb26_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['name'], name='journal_name_8fc3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['-created_at'], name='journal_created_def35d_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['id'], name='papers_id_beb648_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['conference'], name='papers_confere_399127_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['journal'], name='papers_journal_c6b902_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['id'], name='user_profil_id_bf9965_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created_at'], name='user_profil_created_bba55d_idx'),
        ),
    ]
