# Generated by Django 5.2 on 2025-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_api", "0006_conference_journal_alter_paper_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="additional_keywords",
            field=models.TextField(blank=True),
        ),
    ]
