# Generated by Django 5.2 on 2026-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0006_conference_conference_id_26d896_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='category',
            field=models.CharField(choices=[('core', 'CORE / ranked'), ('others', 'Others (placeholder)'), ('custom', 'Custom')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='conference',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='True for bucket conferences (e.g. Others) used before final venue mapping.'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['category'], name='conference_categor_952d09_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['is_placeholder'], name='conference_is_plac_54b1ad_idx'),
        ),
    ]
