# Generated by Django 5.2 on 2025-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_api", "0007_profile_additional_keywords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="institution",
            new_name="faculty_institute",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="role",
            new_name="position",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_scholar_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="additional_keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="research_interests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
