# Generated by Django 5.2 on 2026-05-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0007_conference_category_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_key', models.CharField(max_length=128, unique=True)),
                ('lookup_type', models.CharField(choices=[('doi', 'DOI'), ('title', 'Title')], max_length=10)),
                ('lookup_value', models.CharField(blank=True, max_length=500)),
                ('candidates', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venue_lookup_cache',
                'indexes': [models.Index(fields=['lookup_type'], name='venue_looku_lookup__098cf3_idx'), models.Index(fields=['-fetched_at'], name='venue_looku_fetched_c65ea1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaperVenueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok_auto', 'OK auto'), ('review', 'Review'), ('no_match_db', 'No match in DB'), ('no_venue', 'No venue')], db_index=True, default='pending', max_length=20)),
                ('input_doi', models.CharField(blank=True, max_length=200)),
                ('resolved_doi', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=80)),
                ('venue_from_api', models.CharField(blank=True, max_length=500)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('api_source', models.CharField(blank=True, max_length=80)),
                ('year', models.CharField(blank=True, max_length=16)),
                ('db_venue_kind', models.CharField(blank=True, max_length=20)),
                ('db_venue_id', models.UUIDField(blank=True, null=True)),
                ('db_venue_name', models.CharField(blank=True, max_length=255)),
                ('db_venue_fuzzy_score', models.FloatField(blank=True, null=True)),
                ('no_match_db_payload', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('candidates_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_mapping_result', to='public_api.paper')),
            ],
            options={
                'db_table': 'paper_venue_mapping',
                'indexes': [models.Index(fields=['status'], name='paper_venue_status_e31f14_idx'), models.Index(fields=['lookup_key'], name='paper_venue_lookup__76bb47_idx')],
            },
        ),
    ]
