# Generated by Django 5.2 on 2026-05-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0008_venue_mapping_scale'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conference',
            name='conference_categor_952d09_idx',
        ),
        migrations.RemoveIndex(
            model_name='conference',
            name='conference_is_plac_54b1ad_idx',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='is_placeholder',
        ),
    ]
