# Generated by Django 5.2 on 2026-06-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_api', '0011_chat_session_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='research_ch_session_18f244_idx',
            old_name='research_ch_session_6c1a8e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='research_ch_session_544160_idx',
            old_name='research_ch_session_9b2c4f_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='research_ch_user_id_fd5cc8_idx',
            old_name='research_ch_user_id_8a4f2d_idx',
        ),
    ]
